version: '3.4'

services:
  cms:
    image: ${DOCKER_REGISTRY-}cms
    build:
      context: .
      dockerfile: CMS/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
  
